name = "QNSectors"
uuid = "8d65cbcf-bd1a-4eac-9fbf-652b498c346c"
authors = ["Andreas Feuerpfeil <development@manybodylab.com>"]
version = "0.1.0"

[weakdeps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"

[extensions]
QNSectorsHDF5Ext = "HDF5"

[compat]
HDF5 = "0.17.2"
julia = "1.10"
